export const PLAY_PAUSE = '[OpenDoor] Play / Pause'
export const SHOW_ANSWERS = '[OpenDoor] Show answers'
export const BACK_TO_SELECTION = '[OpenDoor] Back to selection'
export const CHOOSE_VIDEO = '[OpenDoor] Choose video'
export const FOUND_ANSWER = '[OpenDoor] Found answer'
export const START = '[OpenDoor] Start'
export const STOP = '[OpenDoor] Stop'
export const TO_POSTROUND = '[OpenDoor] To PostRound'
