export const FOUND_ANSWER = '[Finale] Found answer'
export const START = '[Finale] Start'
export const STOP = '[Finale] Stop'
export const TO_POSTROUND = '[Finale] To PostRound'
export const NEXT_ROUND = '[Finale] Next Round'
