export const NEXT_GAME = '[Game Manager] Next game'
export const START_GAME = '[Game Manager] Start game'
export const START_COUNTDOWN = '[Game Manager] Start countdown'
export const STOP_COUNTDOWN = '[Game Manager] Stop countdown'
export const MODIFY_SCORE = '[Game Manager] Modify score'
export const SWITCH_PLAYER = '[Game Manager] Switch player'
export const INITIALIZE_GAME = '[Game Manager] Initialize game'
